### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [NeoBlocks/neoblocks-common#1]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/NeoBlocks/neoblocks-common/blob/master/package.json#L37

See https://nodejs.org/api/fs.html

You might want to remove it using `npm uninstall fs`.

**Comment by ThomasLobker** [comment]
Thanks for noticing @DanielRuf :+1: This has been fixed now in version `1.0.1`
